ProjectDIAM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views #import this

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls')),
    path("", include('auth_user.urls')),
    path("", include('Movies.urls')),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="main/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='main/password_reset_complete.html'),
         name='password_reset_complete'),

]

auth_user/urls.py
from django.urls import path
from . import views

app_name = 'auth_user'

urlpatterns = [
    path("register", views.register, name='register'),
    path("logout", views.logout_view, name='logout'),
    path("login", views.login_view, name='login'),
    path("user_profile", views.user_profile, name='user_profile'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path("new_password", views.new_password, name='new_password'),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path("delete_movie_watchlist/<movie_id>", views.delete_movie_watchlist, name="delete_movie_watchlist"),
]

main/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.index, name='index'),
]

auth_user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

GENDER_CHOICES = (
    ("", "Please select"),
    ("M", 'Men'),
    ("F", 'Woman'),
    ("O", 'Other'),
    ("N", 'Rather not Say')
)


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    birthday = models.DateField()
    entry_date = models.DateField(auto_now_add=True)
    block_coin = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


        

main/models.py
from django.db import models

# Create your models here.

auth_user/forms.py
from datetime import datetime, timedelta
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core.validators import validate_email

GENDER_CHOICES = (
    ("", "Please select"),
    ("M", 'Men'),
    ("F", 'Woman'),
    ("O", 'Other'),
    ("N", 'Rather not Say')
)


class RegisterForm(forms.Form):
    firstname = forms.CharField(required=True, label="First name",
                                widget=forms.TextInput(attrs={"class": "form-control"}))
    lastname = forms.CharField(required=True, label="Last Name",
                               widget=forms.TextInput(attrs={"class": "form-control"}))
    user_email = forms.EmailField(required=True, label="E-mail", widget=forms.TextInput(
        attrs={"class": "form-control", "aria-describedby": "inputGroupPrepend"}))
    birthday = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', "class": "form-control"}), required=True, label="Birthday")
    gender = forms.ChoiceField(required=False, choices=GENDER_CHOICES,
                               widget=forms.Select(attrs={"class": "form-select"}), label="Gender")

    def clean(self):
        cd = self.cleaned_data
        username = cd.get('user_email')
        date = cd.get('birthday')

        if not cd.get("firstname"):
            self.add_error("firstname", "Missing first name.")

        if not cd.get("lastname"):
            self.add_error("lastname", "Missing first name.")

        if validate_email(username):
            self.add_error("user_email", "Please provide a valid e-mail")

        if User.objects.filter(username=username):
            self.add_error("user_email", "User is already in use. Please select another.")

        if not cd.get("gender"):
            self.add_error("gender", "Please select a Gender")

        time_between_insertion = datetime.now().date()
        if (time_between_insertion - date) // timedelta(days=365.2425) < 18:
            self.add_error("birthday", "You need to be +18")

        return self.cleaned_data


class PasswordForm(forms.Form):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}), label="Password")
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}), label="Repeat Password")

    def clean(self):
        cd = self.cleaned_data
        password = cd.get("password1")
        password2 = cd.get("password2")

        try:
            validate_password(password)
        except forms.ValidationError as error:
            self.add_error('password1', error)

        if password != password2:
            self.add_error("password2", "Passwords are different please re-enter")

        return self.cleaned_data


class ResetForm(forms.Form):
    user_email = forms.EmailField(required=True, label="E-mail", widget=forms.TextInput(
        attrs={"class": "form-control", "aria-describedby": "inputGroupPrepend"}))

    def clean(self):
        cd = self.cleaned_data
        username = cd.get('user_email')
        if not User.objects.filter(username=username):
            self.add_error("user_email", "Please provide a valid e-mail")


class RechargeForm(forms.Form):
    coinsinput = forms.IntegerField(required=True, min_value=15, max_value=2000, widget=forms.TextInput(attrs={
        "class": "form-control", "aria-describedby": "inputGroup-sizing-default", 'type': 'number', 'min': 15}))

    def clean(self):
        cd = self.cleaned_data
        coin_input = cd.get("coinsinput")
        print(coin_input)
        if not str(coin_input).isdecimal():
            self.add_error("coinsinput", "Please provide a number!")

        if coin_input < 15:
            self.add_error("coinsinput", "Minimum Recharge: 15 BlockCoins")

        if coin_input > 2000:
            self.add_error("coinsinput", "Maximum Recharge: 2000 BlockCoins")

auth_user/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.template.loader import get_template
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from Movies.models import Movies, RechargeRequest, Renting, Request, Watchlist
from Movies.utils import check_rent
from ProjectDIAM.settings import EMAIL_HOST_USER
from .forms import RegisterForm, PasswordForm
from .models import Client
import datetime


# View do registo de um novo utilizador
from .token import account_activation_token, TokenGenerator


def register(request):
    # criado formulários para fazer validar os dados
    form = RegisterForm()
    password_form = PasswordForm()
    if request.method == "POST":
        form = RegisterForm(request.POST or None)
        password_form = PasswordForm(request.POST or None)
        if form.is_valid() and password_form.is_valid():
            try:
                email = request.POST['user_email']
                password = request.POST['password1']
                new_user = User.objects.create_user(first_name=request.POST['firstname'],
                                                    last_name=request.POST['lastname'],
                                                    username=email, password=password, email=email, is_active=False)

                # cria a entrada do cliente
                ut = Client(user=new_user, birthday=request.POST['birthday'], gender=request.POST['gender'])
                ut.save()

                # Enviar e-mail ao cliente de welcome
                context = {"user": new_user,
                           'domain': '127.0.0.1:8000',
                           "uid": urlsafe_base64_encode(force_bytes(new_user.pk)),
                           'token': account_activation_token.make_token(new_user),
                           'protocol': 'http',
                           }
                html = get_template('email/register_email.html').render(context)
                send_mail('Welcome to Blockbuster', 'Welcome message!', EMAIL_HOST_USER, [email], html_message=html,
                          fail_silently=True)
                messages.success(request, "Registration successful! You will received an e-mail for confirmation! ")
                return redirect("index")
            except KeyError:
                messages.error(request, "There was a problem with your register!")

    context = {"register_form": form, "password_form": password_form}
    return render(request, "main/register.html", context=context)


def login_view(request):
    if request.method == 'POST':
        try:
            user_auth = authenticate(username=request.POST['username'], password=request.POST['password'])
            login(request, user_auth)
            messages.success(request, "Welcome " + request.user.first_name)
        except (KeyError, AttributeError):
            messages.error(request, "Couldn't Login")
    return HttpResponseRedirect(reverse('index'))


@login_required()
def logout_view(request):
    logout(request)
    return redirect("index")


# Alteração da password por parte do cliente
@login_required()
def new_password(request):
    password_form = PasswordForm()
    if request.method == 'POST':
        password_form = PasswordForm(request.POST or None)
        if password_form.is_valid():
            try:
                u = User.objects.get(username=request.user.username)
                u.set_password(request.POST['password1'])
                u.save()

                # Ao alterar faz o login de novo de forma a manter o utilizador logado
                user_auth = authenticate(username=u.username, password=request.POST['password1'], email=u.email)

                if user_auth is not None:
                    login(request, user_auth)
                    context = {"user": u}

                    # Email avisar que foi alterada a password
                    html = get_template('email/change_password.html').render(context)
                    send_mail('Change Password', 'Change Password', EMAIL_HOST_USER, [u.email], html_message=html,
                              fail_silently=True)
                    messages.success(request, "Password change successful.")
                    return redirect('auth_user:user_profile')
                else:
                    messages.error(request, "There was a problem resetting your password")
            except KeyError:
                messages.error(request, "There was a problem resetting your password")
            return redirect("auth_user:user_profile")

    context = {"user": request.user, "password_form": password_form}
    return render(request, "main/changePassword.html", context=context)


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    html = get_template('email/reset_password.html').render(c)
                    try:
                        send_mail(subject, subject, EMAIL_HOST_USER, [user.email], fail_silently=True,
                                  html_message=html)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
            else:
                messages.error(request, "User not found.")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="main/password_reset.html",
                  context={"password_reset_form": password_reset_form})


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Thank you for your email confirmation. Now you can login your account.')
        return redirect('index')
    else:
        messages.error(request, 'Activation link is invalid!')
        return redirect('index')


# Pagina profile do cliente
@login_required()
def user_profile(request):
    user_client = Client.objects.get(user=request.user)

    if request.method == 'POST' and request.POST:
        uti = RechargeRequest.objects.filter(client=user_client, recharge_state="Requested")
        if uti.count() == 0:
            new_amount = int(request.POST["coinsinput"])
            RechargeRequest.objects.create(client=user_client, coin_amount=new_amount)
            messages.success(request,
                             "Your request has been submitted. Please wait for our approval before trying to rent any "
                             "movie")
        else:
            messages.error(request, "You already made a recharge request. Please wait for its approval")
        return redirect('auth_user:user_profile')

    # Watch Movies
    watch = Watchlist.objects.filter(client=user_client).values()
    # Rented Movies
    rented = Renting.objects.filter(client=user_client).values()
    check_rent()
    movie_rented = []
    his_movie_rented = []
    if rented.count() > 0:
        for i in rented:
            movie_data = Movies.objects.get(pk=int(i['movies_id']))
            if i['rent_state'] == "Available":
                movie_rented.append({'movie': movie_data, "rent": i})
            else:
                his_movie_rented.append({'movie': movie_data, "rent": i})

    # Request Movies
    re_quest = Request.objects.filter(client=user_client).values()

    user_time = user_client.birthday
    user_time_month = user_time.strftime("%B")
    bb_client = user_client.block_coin
    days_passed = datetime.date.today() - user_time
    d = days_passed.days
    if days_passed.days > 200:
        d = 0
    
    context = {
        'bb_client': bb_client,
        'days_passed': d,
        'user_time': user_time,
        'user_time_month': user_time_month,
        'watch': watch,
        'movie_rented': movie_rented,
        're_quest': re_quest,
        'his_movie_rented': his_movie_rented,
    }

    return render(request, 'main/profile.html', context)


def delete_movie_watchlist(request, movie_id):
    dele = Watchlist.objects.get(client=Client.objects.get(user=request.user), w_movie_id=movie_id)
    dele.delete()
    
    return redirect('auth_user:user_profile')

main/views.py
from django.shortcuts import render
from tmdbv3api import TMDb, Movie

from ProjectDIAM.settings import TMDB_API_KEY

# criar a API para ser usada nas views
tmdb = TMDb()
tmdb.api_key = TMDB_API_KEY
movie = Movie()


# Mostra o index da pagina com um conjunto de listas de filmes
def index(request):
    list_rows_index = [{"name": "Popular", "list": movie.popular()}, {"name": "Latest", "list": movie.now_playing()},
                       {"name": "Top Rated", "list": movie.top_rated()}]

    context = {
        'user': request.user,
        'lists': list_rows_index,
    }

    return render(request, 'main/index.html', context)


def navbar(request):
    context = {'user': request.user}
    return render(request, 'main/navbar.html', context)

auth_user/templates/main/changePassword.html
{% extends 'base.html' %}

<title>{% block title %}Change Password{% endblock %}</title>

{% block content %}
    <div class="row align-items-center">
        <div class="col mb-5">
            {% if user.is_authenticated %}
                <h1>Change Password</h1>
            {% else %}
                <h1>Reset password</h1>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col col-sm-2">
        </div>
        <div class="col shadow p-3 mb-5 bg-body rounded border border-2 border-warning">
            <form class="row g-3 needs-validation"
                  action="{% if not user.is_authenticated %} {% url 'auth_user:reset_password' %} {% else %}  {% url 'auth_user:new_password' %} {% endif %}"
                  method="post" novalidate>
                {% csrf_token %}
                <div class="row p">
                    {% if not user.is_authenticated %}
                        <div class="col-md-4">
                            <label for="{{ reset_form.user_email.id_for_label }}" class="form-label">E-mail <span
                                    class="text-danger">*</span></label>
                            <div class="input-group ">
                                <span class="input-group-text" id="inputGroupPrepend">@</span>
                                {{ reset_form.user_email }}
                                {% if reset_form.user_email.errors %}
                                    <div class="text-danger">
                                        {{ reset_form.user_email.errors }}
                                    </div>
                                {% else %}
                                    <div class="invalid-feedback">
                                        Please provide your e-mail.
                                    </div>
                                {% endif %}

                            </div>
                        </div>
                    {% endif %}
                    <div class="row">
                        <div class="col-md-4">
                            <label for="{{ password_form.password1.id_for_label }}" class="form-label">Password <span
                                    class="text-danger">*</span></label>
                            {{ password_form.password1 }}

                            {% if password_form.password1.errors %}
                                <div class="text-danger">
                                    {{ password_form.password1.errors }}
                                </div>
                            {% else %}
                                <div class="invalid-feedback">
                                    Please provide a password.
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-4">
                            <label for="{{ password_form.password2.id_for_label }}" class="form-label">Re-enter Password
                                <span class="text-danger">*</span></label>
                            {{ password_form.password2 }}
                            {% if password_form.password2.errors %}
                                <div class="text-danger">
                                    {{ password_form.password2.errors }}
                                </div>
                            {% else %}
                                <div class="invalid-feedback">
                                    Please repeat password.
                                </div>
                            {% endif %}

                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <br>
                        <button class="btn btn-warning" type="submit">Recover Password</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col col-sm-2">
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict'

            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.querySelectorAll('.needs-validation')

            // Loop over them and prevent submission
            Array.prototype.slice.call(forms)
                .forEach(function (form) {
                    form.addEventListener('submit', function (event) {
                        if (!form.checkValidity()) {
                            event.preventDefault()
                            event.stopPropagation()
                        }

                        form.classList.add('was-validated')
                    }, false)
                })
        })()
    </script>
{% endblock %}

auth_user/templates/main/password_reset.html
{% extends 'base.html' %}

<title>{% block title %}Password Reset{% endblock %}</title>

{% block content %}

	<!--Reset Password-->
	<div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Reset Password</h2>
		<hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ password_reset_form.as_p }}
            <button class="btn btn-warning" type="submit">Send email</button>
        </form>
  	</div>

{% endblock %}

auth_user/templates/main/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="/login" class="btn btn-warning">Log in</a>
    </div>

{% endblock %}

auth_user/templates/main/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}


  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-warning" type="submit">Reset password</button>
        </form>
    </div>

{% endblock %}

auth_user/templates/main/register.html
<!-- TEMPLATE BASE -->
{% extends 'base.html' %}

<title>{% block title %}Register{% endblock %}</title>

{% block content %}
    <div class="row align-items-center">
        <div class="col mb-5">
            <h1>Welcome to BlockBuster!</h1>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col col-sm-2">
        </div>
        <div class="col shadow p-3 mb-5 bg-body rounded border border-2 border-warning">
            <form class="row g-3 needs-validation"
                  action="{% url 'auth_user:register' %}" method="post" novalidate>
                {% csrf_token %}
                <div class="row p">
                    <div class="col-md-4">
                        <label for="{{ register_form.firstname.id_for_label }}" class="form-label">First name <span
                                class="text-danger">*</span></label>
                        {{ register_form.firstname }}
                        {% if register_form.firstname.errors %}
                            <div class="text-danger">
                                {{ register_form.firstname.errors }}
                            </div>
                        {% else %}
                            <div class="invalid-feedback">
                                Please provide your first name.
                            </div>
                        {% endif %}

                    </div>
                    <div class="col-md-4">
                        <label for="{{ register_form.lastname.id_for_label }}" class="form-label">Last name <span
                                class="text-danger">*</span></label>
                        {{ register_form.lastname }}
                        {% if register_form.lastname.errors %}
                            <div class="text-danger">
                                {{ register_form.lastname.errors }}
                            </div>
                        {% else %}
                            <div class="invalid-feedback">
                                Please provide your first name.
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-4">
                        <label for="{{ register_form.user_email.id_for_label }}" class="form-label">E-mail <span
                                class="text-danger">*</span></label>
                        <div class="input-group ">
                            <span class="input-group-text" id="inputGroupPrepend">@</span>
                            {{ register_form.user_email }}
                            {% if register_form.user_email.errors %}
                                <div class="text-danger">
                                    {{ register_form.user_email.errors }}
                                </div>
                            {% else %}
                                <div class="invalid-feedback">
                                    Please provide your e-mail.
                                </div>
                            {% endif %}

                        </div>
                    </div>
                    <div class="col-md-4">
                        <label for="{{ register_form.birthday.id_for_label }}" class="form-label">Birthday <span
                                class="text-danger">*</span></label>
                        {{ register_form.birthday }}
                        {% if register_form.birthday.errors %}
                            <div class="text-danger">
                                {{ register_form.birthday.errors }}
                            </div>
                        {% else %}
                            <div class="invalid-feedback">
                                Please select your birth date!
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-4">
                        <label for="{{ register_form.gender.id_for_label }}" class="form-label">Gender <span
                                class="text-danger">*</span></label>
                        {{ register_form.gender }}
                        {% if register_form.gender.errors %}
                            <div class="text-danger">
                                {{ register_form.gender.errors }}
                            </div>
                        {% else %}
                            <div class="invalid-feedback">
                                Please select your gender.
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label for="{{ password_form.password1.id_for_label }}" class="form-label">Password <span
                                class="text-danger">*</span></label>
                        {{ password_form.password1 }}

                        {% if password_form.password1.errors %}
                            <div class="text-danger">
                                {{ password_form.password1.errors }}
                            </div>
                        {% else %}
                            <div class="invalid-feedback">
                                Please provide a password.
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-4">
                        <label for="{{ password_form.password2.id_for_label }}" class="form-label">Re-enter Password
                            <span class="text-danger">*</span></label>
                        {{ password_form.password2 }}
                        {% if password_form.password2.errors %}
                            <div class="text-danger">
                                {{ password_form.password2.errors }}
                            </div>
                        {% else %}
                            <div class="invalid-feedback">
                                Please repeat password.
                            </div>
                        {% endif %}

                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="form-check">
                            <br>
                            <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                            <label class="form-check-label" for="invalidCheck">
                                Agree to terms and conditions
                            </label>
                            <div class="invalid-feedback">
                                You must agree before submitting.
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <br>
                        <button class="btn btn-warning" type="submit">Register</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col col-sm-2">

        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict'

            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.querySelectorAll('.needs-validation')

            // Loop over them and prevent submission
            Array.prototype.slice.call(forms)
                .forEach(function (form) {
                    form.addEventListener('submit', function (event) {
                        if (!form.checkValidity()) {
                            event.preventDefault()
                            event.stopPropagation()
                        }

                        form.classList.add('was-validated')
                    }, false)
                })
        })()
    </script>
{% endblock %}