Movies/urls.py
from . import views
from django.urls import path

app_name = 'Movies'
urlpatterns = [
    path('search_details', views.search_details, name="search_details"),
    path('movie_details/<movie_id>', views.movie_details, name="movie_details"),
    path('watchlist_add/<movie_id>', views.watchlist_add, name="watchlist_add"),
    path('movie_rent/<movie_id>', views.movie_rent, name="movie_rent"),
    path('movie_request/<movie_id>', views.movie_request, name="movie_request"),
    path('watch_movie/<movie_id>', views.watch_movie, name="watch_movie"),
]

ProjectDIAM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views #import this

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls')),
    path("", include('auth_user.urls')),
    path("", include('Movies.urls')),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="main/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='main/password_reset_complete.html'),
         name='password_reset_complete'),

]

auth_user/urls.py
from django.urls import path
from . import views

app_name = 'auth_user'

urlpatterns = [
    path("register", views.register, name='register'),
    path("logout", views.logout_view, name='logout'),
    path("login", views.login_view, name='login'),
    path("user_profile", views.user_profile, name='user_profile'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path("new_password", views.new_password, name='new_password'),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path("delete_movie_watchlist/<movie_id>", views.delete_movie_watchlist, name="delete_movie_watchlist"),
]

main/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.index, name='index'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from tmdbv3api import TMDb, Movie

from ProjectDIAM.settings import TMDB_API_KEY

# criar a API para ser usada nas views
tmdb = TMDb()
tmdb.api_key = TMDB_API_KEY
movie = Movie()


# Mostra o index da pagina com um conjunto de listas de filmes
def index(request):
    list_rows_index = [{"name": "Popular", "list": movie.popular()}, {"name": "Latest", "list": movie.now_playing()},
                       {"name": "Top Rated", "list": movie.top_rated()}]

    context = {
        'user': request.user,
        'lists': list_rows_index,
    }

    return render(request, 'main/index.html', context)


def navbar(request):
    context = {'user': request.user}
    return render(request, 'main/navbar.html', context)

main/templates/main/footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 text-white border-top border-warning border-4 bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <p class="col-md-4 mb-0 text-white">&copy; 2022 BlockBuster, Inc</p>

            <a href="#top"
               class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto text-warning link-dark text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                     class="bi bi-bootstrap" viewBox="0 0 16 16">
                    <path d="M5.062 12h3.475c1.804 0 2.888-.908 2.888-2.396 0-1.102-.761-1.916-1.904-2.034v-.1c.832-.14 1.482-.93 1.482-1.816 0-1.3-.955-2.11-2.542-2.11H5.062V12zm1.313-4.875V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23H6.375zm0 3.762V8.162h1.822c1.236 0 1.887.463 1.887 1.348 0 .896-.627 1.377-1.811 1.377H6.375z"></path>
                    <path d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4zm4-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3H4z"></path>
                </svg>
            </a>

            <ul class="nav col-md-4 justify-content-end">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-white">Home</a></li>
            </ul>
        </div>
    </div>
</footer>

main/templates/main/index.html
<!-- TEMPLATE BASE -->
{% extends 'base.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block css_extra %}
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>

    <style>
        .owl-stage {
            display: flex;
        }

        .owl-item {
            display: flex;
            flex: 1 0 auto;
        }

    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col  text-center">
            <img src="{% static 'images/logo/Artboard 3@4x.png' %}" width="500" height="500" class="float-center"
                 alt="BlockBuster Logo">

        </div>
        <div class="col justify-content-center text-center d-flex flex-column">
            <h3>Welcome to BlockBuster, Your window to the awesomeness of movies.<br>
                View want you want, when you want!
                <i class="bi bi-hand-thumbs-up-fill"></i>
            </h3>

        </div>
    </div>
    {% for list in lists %}
        <hr class="style5">
        <div class="row">
            <h2>{{ list.name }}</h2>
            <div class="owl-carousel owl-theme">
                {% for i in list.list %}
                    <div class="col-sm-3 p-2 h-100">
                        <div class="card border border-2 border-warning h-100" style="width: 18rem;">
                            <img src="https://image.tmdb.org/t/p/w500/{{ i.poster_path }}"
                                 class="card-img-top rounded img-fluid img-thumbnail"
                                 width="100" height="250" alt="{{ i.title }}">
                            <div class="card-body" style="width: 18rem;">
                                <h5 class="card-title">{{ i.title }}</h5>
                                <p class="card-text">{{ i.overview|truncatechars:75 }}</p>
                            </div>
                            <ul class="list-group list-group-flush" style="border: none">
                                <li class="list-group-item"><span
                                        class="badge rounded-pill bg-warning text-dark">{{ i.vote_average }} / 10</span>
                                </li>
                            </ul>
                            <div class="card-footer text-muted">
                                <a href="{% url 'Movies:movie_details' i.id %}" class="btn btn-warning">Details</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}


{% endblock %}

{% block javascript %}
    <script>
        $('.owl-carousel').owlCarousel({
            autoplay: true,
            autoplayTimeout: 1500,
            autoplayHoverPause: true,

            center: false,
            rewind: true,

            mouseDrag: true,
            touchDrag: true,
            pullDrag: true,
            freeDrag: false,

            margin: 0,
            stagePadding: 0,

            merge: false,
            mergeFit: true,
            autoWidth: false,

            startPosition: 0,
            rtl: false,

            smartSpeed: 1000,
            fluidSpeed: false,
            dragEndSpeed: false,
            responsive: {
                0: {
                    items: 1,
                    nav: true
                },
                480: {
                    items: 2,
                    nav: false
                },
                768: {
                    items: 3,
                    nav: true,
                    loop: true
                },
                992: {
                    items: 4,
                    nav: true,
                    loop: true
                }
            },

            navText: ['<button type="button" class="btn btn-warning btn-lg"><i class="bi bi-arrow-left-circle-fill"></i></button>', '<button type="button" class="btn btn-warning btn-lg"><i class="bi bi-arrow-right-circle-fill"></i></button>']
        });
    </script>
{% endblock %}

main/templates/main/messages.html
{% for message in messages %}
    <div class="pd-3 alert {{ message.tags }} alert-dismissible fade show" style="text-align: center" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        {{ message }}
    </div>
{% endfor %}

<!-- Auto clear as mensagens -->
<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 2500);
</script>

main/templates/main/navbar.html
<header class="p-3 bg-dark text-white sticky-top border-bottom border-warning border-4">
    <div class="container">
        <div class="row">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="{% url 'index' %}"
                   class="d-flex align-items-center mb-2 mb-lg-0 text-warning text-decoration-none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                         class="bi bi-bootstrap" viewBox="0 0 16 16">
                        <path d="M5.062 12h3.475c1.804 0 2.888-.908 2.888-2.396 0-1.102-.761-1.916-1.904-2.034v-.1c.832-.14 1.482-.93 1.482-1.816 0-1.3-.955-2.11-2.542-2.11H5.062V12zm1.313-4.875V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23H6.375zm0 3.762V8.162h1.822c1.236 0 1.887.463 1.887 1.348 0 .896-.627 1.377-1.811 1.377H6.375z"></path>
                        <path d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4zm4-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3H4z"></path>
                    </svg>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'index' %}" class="nav-link px-2 text-white">Home</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 form-floating"
                      action="{% url 'Movies:search_details' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group ">
                        <label for="search">
                            <input type="text" class="form-control form-control-dark" id="search"
                                   placeholder="Search..."
                                   name="search_input" required>
                        </label>
                        <button class="btn btn-outline-warning" type="submit" id="button-addon2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-search" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                            </svg>
                        </button>
                    </div>
                </form>
                {% if not user.is_authenticated %}
                    <div class="text-end">
                        <button class="btn btn-outline-light me-2" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                            Login
                        </button>
                        <a href="{% url 'auth_user:register' %}">
                            <button type="button" class="btn btn-warning">Registar</button>
                        </a>
                    </div>

                {% else %}
                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="https://api.multiavatar.com/{{ request.user.get_full_name }}.png" alt="mdo" width="32" height="32"
                                 class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                            <li><a class="dropdown-item" href="{% url 'auth_user:user_profile' %}">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'auth_user:logout' %}">Sign out</a></li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 ms-auto">
                <div class="collapse " id="collapseExample">
                    <div class="card card-body bg-dark text-white">
                        <form method="post" class="needs-validation" action="{% url 'auth_user:login' %}" novalidate>
                            {% csrf_token %}
                            <input type="hidden" name="next_link" value="{{ request.path }}">
                            <div class="row mb-3">
                                <label for="username" class="col-sm-3 col-form-label">Username</label>
                                <div class="col-sm-8">
                                    <input type="email" class="form-control" id="username" name="username"
                                           aria-describedby="inputGroupPrepend" required>
                                    <div class="invalid-feedback">
                                        Please provide a username.
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="password" class="col-sm-3 col-form-label">Password</label>
                                <div class="col-sm-8">
                                    <input type="password" class="form-control" id="password" name="password" required>
                                    <div class="invalid-feedback">
                                        Please provide a Password.
                                    </div>
                                </div>

                            </div>
                            <button type="submit" class="btn btn-warning">Log in</button>
                            <a href="{% url 'auth_user:password_reset' %}">
                            <button type="button" class="btn btn-outline-warning">Forgot Password</button></a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<a name="top"></a>
<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>